language: cpp

before_script:
# Installing SFML
#- cd ../
#- wget https://www.sfml-dev.org/files/SFML-2.5.0-linux-gcc-64-bit.tar.gz
#- tar -xzf SFML-2.5.0-linux-gcc-64-bit.tar.gz
#- mv -v ./SFML-2.5.0/include/* ./Conure2D/
script:
- eval "${MATRIX_EVAL}"
# Building Conure2D
#- cd Conure2D
- pwd
- mkdir Build
- cd Build
- cmake .. ${BUILD_TYPE}
- sudo make

matrix:
  fast_finish: true
  include:
    # Linux, GCC, Debug
    - os: linux
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libxrandr-dev
            - libudev-dev
            - libopenal-dev
            - libvorbis-dev
            - libflac-dev
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        - BUILD_TYPE="-DCMAKE_BUILD_TYPE=Debug"
      # Linux, GCC, Release
    - os: linux
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        - BUILD_TYPE="-DCMAKE_BUILD_TYPE=Release"
    # Linux, GCC, Production
    - os: linux
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        - BUILD_TYPE="-DCMAKE_BUILD_TYPE=Production"
    # Linux, Clang, Debug
    - os: linux
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - g++-8
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
        - BUILD_TYPE="-DCMAKE_BUILD_TYPE=Debug"
    # Linux, Clang, Release
    - os: linux
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - g++-8
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
        - BUILD_TYPE="-DCMAKE_BUILD_TYPE=Release"
    # Linux, Clang, Production
    - os: linux
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - g++-8
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
        - BUILD_TYPE="-DCMAKE_BUILD_TYPE=Production"