language: cpp
sudo: required
compiler:
  - gcc
os:
  - linux
before_script:
  - echo Installing gcc-8
  - sudo apt-get install -y gcc-8 g++-8
  - wget https://cmake.org/files/v3.12/cmake-3.12.0-rc3.tar.gz
  - tar xzf cmake-3.12.0-rc3.tar.gz
  - cd cmake-3.12.0-rc3
  - ./bootstrap
  - make
  - make install
  - cd ~
  - mkdir build
  - cd build
  - cmake ..
script: make
