language: cpp
sudo: required
compiler:
  - gcc
os:
  - linux
before_script:
  - cd /home/travis/build/Vismar/
  - echo Installing gcc-8
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt update
  - sudo apt-get install -y gcc-8 g++-8
  - wget https://cmake.org/files/v3.12/cmake-3.12.0-rc3.tar.gz
  - tar xzf cmake-3.12.0-rc3.tar.gz
  - cd cmake-3.12.0-rc3
  - ./bootstrap
  - make
  - sudo make install
  - cd /home/travis/build/Vismar/Conure2D
  - mkdir build
  - cd build
  - cmake ..
script: make
